### ISSUE TITLE
RuntimeError: Could not set URL

### ISSUE THREAD

**Issue by dhirschfeld** [TheSnakePit/mamba#417]
I can reliably reproduce this error on win64 if the environment being installed into does not contain a `conda-bld` ***directory***.
```
RuntimeError: Could not set URL (code: 4 - url = :\Users\dhirschf\envs\py38\conda-bld)
```
In this case `mamba` creates a `conda-bld` ***file*** in the root directory of the env and you get the runtime error.

<details>
<summary>Details</summary>

```
(base) C:\> conda create -n py38 python=3.8
(base) C:\> conda activate py38
(py38) C:\> mamba install escapism

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.4.2) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/main/win-64         [====================] (00m:00s) No change
pkgs/msys2/win-64        [====================] (00m:00s) No change
pkgs/msys2/noarch        [====================] (00m:00s) No change
external/noarch          [====================] (00m:00s) No change
external/win-64          [====================] (00m:00s) No change
stanwell/uat/win-64      [====================] (00m:00s) Done
stanwell/uat/noarch      [====================] (00m:00s) No change
conda-forge/noarch       [====================] (00m:01s) Done
conda-forge/win-64       [====================] (00m:07s) Done

Looking for: ['escapism']


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 814, in exception_converter
        raise e
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 808, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 773, in _wrapped_main
        result = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 663, in do_call
        exit_code = install(args, parser, 'install')
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 515, in install
        solver.add_pin(str(s))
    RuntimeError: Could not set URL (code: 4 - url = :\Users\dhirschf\envs\py38\conda-bld)

`$ C:\Miniconda3\Scripts\mamba install escapism`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=py38
                CONDA_EXE=C:\Miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Miniconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\dhirschf\envs\py38
           CONDA_PREFIX_1=C:\Miniconda3
    CONDA_PROMPT_MODIFIER=(py38)
         CONDA_PYTHON_EXE=C:\Miniconda3\python.exe
               CONDA_ROOT=C:\Miniconda3
              CONDA_SHLVL=2
                 HOMEPATH=\Users\dhirschf
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : py38
    active env location : C:\Users\dhirschf\envs\py38
            shell level : 2
       user config file : C:\Users\dhirschf\.condarc
 populated config files : C:\ProgramData\conda\.condarc
                          C:\Users\dhirschf\.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.7.7.final.0

(py38) C:\>
```
</details>

**Comment by wolfv** [comment]
Thanks! We will have to fix this asap. I think this has to do with our channel implementation cc @JohanMabille

**Comment by dhirschfeld** [comment]
Forgot to mention that the workaround is to first create an empty `conda-bld` ***directory*** in the environment root and then `mamba` is happy again.

**Comment by wolfv** [comment]
ah sorry @JohanMabille I have already pushed the fix

**Comment by JohanMabille** [comment]
no worries ;)

**Comment by dhirschfeld** [comment]
It looks like #422 didn't fix the issue, as I'm still seeing it on `0.4.3`:
```
> mamba update black

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.4.3) supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

conda-forge/win-64       Using cache
conda-forge/noarch       Using cache
external/win-64          [====================] (00m:00s) No change
pkgs/main/win-64         [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/msys2/win-64        [====================] (00m:00s) No change
pkgs/msys2/noarch        [====================] (00m:00s) No change
external/noarch          [====================] (00m:00s) No change
stanwell/uat/win-64      [====================] (00m:00s) No change
stanwell/uat/noarch      [====================] (00m:00s) No change

Looking for: ['black']


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 814, in exception_converter
        raise e
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 808, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 773, in _wrapped_main
        result = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 669, in do_call
        exit_code = update(args, parser)
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 579, in update
        install(args, parser, 'update')
      File "C:\Miniconda3\lib\site-packages\mamba\mamba.py", line 515, in install
        solver.add_pin(str(s))
    RuntimeError: Could not set URL (code: 4 - url = :\Miniconda3\conda-bld)

`$ C:\Miniconda3\Scripts\mamba update black`
```

The one difference I can see is that I'm now seeing this error even though the `conda-bld` directory does exist - i.e. this error is now happening all the time for me :(

**Comment by wolfv** [comment]
alright back to the drawing board!

**Comment by wolfv** [comment]
@dhirschfeld sorry about the continuing problems! I have debugged this further, and I can reproduce it on Windows.

The good news: it only affects people who pin packages with a channel :)
The bad news: I don't have a fix yet! The root cause of the problem are urls of the format file://C:/ where the scheme is detected as `file` but we don't handle the drive letter correctly which leaves us with an inconsistent URL / path (`:/Users/Miniconda3/...`).
I'll try to fix this tomorrow or on Monday. Until then either disable the pinnigs or downgrade mamba :'( 

Sorry & cheers!

**Comment by dhirschfeld** [comment]
No probs - downgrading works fine for now!

**Comment by dhirschfeld** [comment]
Upgraded to `0.4.4` and everything seems to be working great!

**Comment by wolfv** [comment]
Awesome
